version: 1
jobs:
run-test-suite:
docker:
- image: circleci/node:10.16.3
working_directory: ~/
steps:
- checkout
- run:
name: Fetch dependencies
command: npm install
- run:
name: Run test suite
command: npm test_ci
- persist_to_workspace:
root: ~/
paths:
- .
workflows:
test-and-deploy:
jobs:
    - run-test-suite